backend:
  name: git-gateway
  branch: master

media_folder: "src/site/assets" # Media files will be stored in the repo under static/images
public_folder: "/assets" # The src attribute for uploaded media will begin with /images

publish_mode: editorial_workflow

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "src/site" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Header image", name: "headerImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

